services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9099:9099"
    volumes:
      - logs:/logs
      - cache:/cache
    healthcheck:
      test: ["CMD-SHELL", "pgrep node || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  logs:
  cache: