name: Deploy to Raspberry Pi via Tailscale

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tailscale
          uses: tailscale/github-action@v2
          with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Deploy to Raspberry Pi
        run: |
          # Replace with your deployment script
          ssh pi@your-tailscale-ip-address 'cd /path/to/your/repo && git pull origin main'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
